name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install DigitalOcean and Helm actions
      uses:
        - digitalocean/action-install-doctl@v1
        - helm/install-helm-2@v1
    - name: Authenticate with DigitalOcean
      uses: digitalocean/action-authenticate@v1
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Install Helm chart
      uses:
        - name: Upgrade Helm chart
          uses: helm/helm-2-upgrade@v1
          with:
            chart: my-chart
            name: my-release
            namespace: default
